export const AXIOS_USERS = 'AXIOS_USERS';
export const BEGIN_LOAD_AXIOS_USERS = 'BEGIN_LOAD_AXIOS_USERS';
export const ERROR_LOAD_AXIOS_USERS = 'ERROR_LOAD_AXIOS_USERS';
export const DELETE_USER = 'DELETE_USERS';
export const ADD_USER = 'ADD_USER';

export const BEGIN_REGISTER_USER = 'BEGIN_REGISTER_USER'
export const REGISTER_USER = 'REGISTER_USER';
export const ERROR_REGISTER_USER = 'ERROR_REGISTER_USER'

export const BEGIN_LOGIN_USER = 'BEGIN_LOGIN_USER'
export const LOGIN_USER = 'LOGIN_USER';
export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER'
export const LOAD_TOKEN = 'LOAD_TOKEN'

export const LOGOUT_USER = 'LOGOUT_USER';
